---
- hosts: all
  become: true
  vars_files:
    - vars/site.yml

  roles:
    - role: common

- hosts: web
  become: true
  vars_files:
    - vars/web.yml
  
  roles:
    - role: datadog.datadog
      become: true