---
- hosts: all
  become: true
  vars_files:
    - vars/site.yml

  roles:
    - role: common

- hosts: web
  become: true
  vars_files:
    - vars/web.yml
  
  #roles:
  #  - role: datadog.datadog
  #    become: true

- hosts: docker
  become: true
  vars_files:
    - vars/docker.yml

  roles:
    - role: docker
      become: true